DO $$ BEGIN
  CREATE TYPE agent_task_operation AS ENUM ('CONVERSATION', 'PLAN', 'REPLAN');
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;
DO $$ BEGIN
  CREATE TYPE agent_task_status AS ENUM (
    'QUEUED', 'RUNNING', 'CANCEL_REQUESTED', 'COMPLETED',
    'FAILED', 'CANCELLED', 'STALE'
  );
EXCEPTION WHEN duplicate_object THEN NULL;
END $$;

ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'AGENT_TASK';

ALTER TABLE chat_messages
  ADD COLUMN IF NOT EXISTS message_sequence BIGINT GENERATED BY DEFAULT AS IDENTITY;

ALTER TABLE chat_messages
  ALTER COLUMN message_sequence SET NOT NULL;

CREATE UNIQUE INDEX IF NOT EXISTS chat_messages_thread_sequence_unique
  ON chat_messages(thread_id, message_sequence);

CREATE TABLE IF NOT EXISTS agent_task_runs (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  operation agent_task_operation NOT NULL,
  status agent_task_status NOT NULL DEFAULT 'QUEUED',
  created_by_user_id UUID NOT NULL REFERENCES users(id),
  thread_id UUID REFERENCES chat_threads(id) ON DELETE CASCADE,
  trip_id UUID REFERENCES shared_trips(id) ON DELETE CASCADE,
  snapshot_id UUID REFERENCES constraint_snapshots(id),
  request_id UUID NOT NULL,
  user_message_id UUID REFERENCES chat_messages(id) ON DELETE CASCADE,
  assistant_message_id UUID REFERENCES chat_messages(id) ON DELETE SET NULL,
  result_plan_id UUID REFERENCES itinerary_plans(id) ON DELETE SET NULL,
  place_source_id VARCHAR(128),
  place_name VARCHAR(160),
  place_latitude DOUBLE PRECISION,
  place_longitude DOUBLE PRECISION,
  place_source_type VARCHAR(16),
  generation_attempt INTEGER NOT NULL DEFAULT 0 CHECK (generation_attempt >= 0),
  attempt_count INTEGER NOT NULL DEFAULT 0 CHECK (attempt_count >= 0),
  max_attempts INTEGER NOT NULL DEFAULT 3 CHECK (max_attempts BETWEEN 1 AND 10),
  lease_token UUID,
  lease_expires_at TIMESTAMPTZ,
  started_at TIMESTAMPTZ,
  finished_at TIMESTAMPTZ,
  cancel_requested_at TIMESTAMPTZ,
  next_attempt_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  expires_at TIMESTAMPTZ NOT NULL,
  error_code VARCHAR(64),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  CONSTRAINT agent_task_runs_operation_refs_check CHECK (
    (operation = 'CONVERSATION' AND thread_id IS NOT NULL AND user_message_id IS NOT NULL
      AND trip_id IS NULL AND snapshot_id IS NULL)
    OR
    (operation IN ('PLAN', 'REPLAN') AND trip_id IS NOT NULL AND snapshot_id IS NOT NULL
      AND thread_id IS NULL AND user_message_id IS NULL)
  ),
  CONSTRAINT agent_task_runs_place_check CHECK (
    (place_name IS NULL AND place_latitude IS NULL AND place_longitude IS NULL AND place_source_type IS NULL)
    OR
    (place_name IS NOT NULL AND place_latitude BETWEEN -90 AND 90
      AND place_longitude BETWEEN -180 AND 180
      AND place_source_type IN ('REFERENCE', 'INSPIRATION'))
  ),
  CONSTRAINT agent_task_runs_terminal_result_check CHECK (
    (assistant_message_id IS NULL OR (operation = 'CONVERSATION' AND status = 'COMPLETED'))
    AND
    (result_plan_id IS NULL OR (operation IN ('PLAN', 'REPLAN') AND status = 'COMPLETED'))
  )
);

CREATE UNIQUE INDEX IF NOT EXISTS agent_task_runs_thread_request_unique
  ON agent_task_runs(thread_id, request_id) WHERE thread_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS agent_task_runs_trip_request_unique
  ON agent_task_runs(trip_id, request_id) WHERE trip_id IS NOT NULL;
CREATE UNIQUE INDEX IF NOT EXISTS agent_task_runs_one_active_conversation
  ON agent_task_runs(thread_id)
  WHERE thread_id IS NOT NULL AND status IN ('QUEUED', 'RUNNING', 'CANCEL_REQUESTED');
CREATE UNIQUE INDEX IF NOT EXISTS agent_task_runs_one_active_planning
  ON agent_task_runs(trip_id)
  WHERE trip_id IS NOT NULL AND status IN ('QUEUED', 'RUNNING', 'CANCEL_REQUESTED');
CREATE INDEX IF NOT EXISTS agent_task_runs_created_by_idx ON agent_task_runs(created_by_user_id);
CREATE INDEX IF NOT EXISTS agent_task_runs_claim_idx
  ON agent_task_runs(status, next_attempt_at, lease_expires_at, created_at);
