ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'FLIGHT_OFFER_CUE_ACCEPT';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'FLIGHT_OFFER_CUE_DISMISS';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'HOTEL_OFFER_CUE_ACCEPT';
ALTER TYPE audit_action ADD VALUE IF NOT EXISTS 'HOTEL_OFFER_CUE_DISMISS';
